from sqlalchemy import create_engine, Column, Integer, String, JSON, DateTime, Date
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import os
import datetime

# Get DB URL from Environment (set in docker-compose)
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./local_history.db") # Fallback to SQLite for non-docker local dev

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

class SessionReport(Base):
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    session_id = Column(String, index=True) # "demo_session_1"
    transcript = Column(String)
    clinical_notes = Column(JSON) # List of strings
    report_json = Column(JSON) # The full Gemini 3 analysis

class DailyPlan(Base):
    __tablename__ = "daily_plans"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, unique=True, index=True) # One plan per day
    plan_json = Column(JSON) # The generated plan (Routine, Thoughts)
    completion_status = Column(JSON, default={}) # {"0": true, "1": false}
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

class ExerciseSession(Base):
    __tablename__ = "exercise_sessions"

    id = Column(Integer, primary_key=True, index=True)
    session_uuid = Column(String, unique=True, index=True) # Generated by Frontend or Backend
    exercise_id = Column(String, index=True) # e.g. 'abduction'
    start_time = Column(DateTime, default=datetime.datetime.utcnow)
    end_time = Column(DateTime, nullable=True)
    status = Column(String, default="started") # started, completed, abandoned
    metrics = Column(JSON, default={}) # {reps: 0, rom: 0, stability: 0}
    
class SessionMetrics(Base):
    __tablename__ = "session_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    session_uuid = Column(String, index=True)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    metric_type = Column(String) # 'rep', 'rom_peak', 'stability_alert'
    value = Column(JSON) # 90, 0.45, etc.

class CustomExercise(Base):
    __tablename__ = "custom_exercises"

    id = Column(String, primary_key=True, index=True) # UUID
    name = Column(String)
    domain = Column(String) # BODY, HAND, FACE
    config_json = Column(JSON)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

def init_db():
    Base.metadata.create_all(bind=engine)
